---
name: 'Prepare Release'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to be released (e.g., 8.24.0)'
        required: true
        type: string
        default: '1.2.3'
      base-branch:
        description: 'The branch to release from.'
        type: choice
        options:
          - main
          - '8.x'
          - mpo
        default: 'mpo'

permissions: {}

jobs:
  prepare_release:
    uses: OpenVoxProject/shared-actions/.github/workflows/prepare_release.yml@main
    with:
      version: ${{ inputs.version }}
      base-branch: ${{ inputs.base-branch }}
    secrets:
      github_pat: ${{ secrets.OPENVOXBOT_COMMIT_AND_PRS }}
      ssh_private_key: ${{ secrets.OPENVOXBOT_SSH_PRIVATE_KEY }}
