---
name: Build openvoxdb

permissions:
  contents: read # minimal required permissions to clone repo

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Tag to build'
        required: true
      deb_platform_list:
        description: 'A comma-separated list of deb-based platforms to build for, excluding the architecture (e.g. ubuntu-24.04,debian-12). Do not include spaces. If not provided, will use the default list of platforms supported by OpenVox Server and DB.'
        required: false
        type: string
      rpm_platform_list:
        description: 'A comma-separated list of rpm-based platforms to build for, excluding the architecture (e.g. el-9,amazon-2023). Do not include spaces. If not provided, will use the default list of platforms supported by OpenVox Server and DB.'
        required: false
        type: string
      ezbake-ref:
        description: |-
          Branch/tag from ezbake that will be used for openvoxdb/server builds.
        type: string
        default: 'main'
      ezbake-ver:
        description: 'The version specified in project.clj in the given ezbake-ref. Will default to the version found in project.clj in this repo if not specified.'
        type: string
        required: false
jobs:
  build:
    uses: 'openvoxproject/shared-actions/.github/workflows/build_ezbake.yml@main'
    with:
      ref: ${{ inputs.ref }}
      deb_platform_list: ${{ inputs.deb_platform_list }}
      rpm_platform_list: ${{ inputs.rpm_platform_list }}
      ezbake-ref: ${{ inputs.ezbake-ref }}
      ezbake-ver: ${{ inputs.ezbake-ver }}
    secrets: inherit
