---
name: daily
on:
  schedule:
    # 12:00 UTC
    - cron: '0 12 * * *'

permissions:
  contents: read # minimal required permissions to clone repo

jobs:
  core:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Change the pb_test_gh_job_id definition below after any
        # additions/removals of matrix axes.  The flavor "/" is
        # converted to "_" in the pdb-job-id below.

        # These run on every branch
        flavor:
          - core+ext/openjdk21/pg-15
          - core+ext/openjdk25/pg-15

        os: [ubuntu-24.04]
        ruby: ['3.4']

        # Defaults for special-case influencing vars
        lein-profile: ['']
        drop-joins: ['']

        # Special cases
        include:
          - os: ubuntu-24.04
            ruby: '3.4'
            flavor: core+ext/openjdk21/pg-16
            drop-joins: by-request
          - os: ubuntu-24.04
            ruby: '3.4'
            flavor: core+ext/openjdk21/pg-16
            lein-profile: fips

          # non-rich variants for main
          - os: ubuntu-24.04
            branch: main
            ruby: '3.4'
            flavor: int/openjdk21/pup-main/srv-main/pg-16

    steps:
      - name: Compute job outputs
        id: computed
        run: |
          # This id must be unique across all jobs
          pdb_test_gh_job_id="${{ matrix.os }}/${{ matrix.flavor }}"
          pdb_test_gh_job_id="${pdb_test_gh_job_id//\//_}"
          pdb_test_gh_job_id+="_${{ matrix.lein-profile }}"
          pdb_test_gh_job_id+="_${{ matrix.drop-joins }}"

          echo "pdb-job-id=$pdb_test_gh_job_id" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ matrix.branch }}
          persist-credentials: false
      - uses: ruby/setup-ruby@8e41b362d2589a22a44c1cfa214b3c83052c195b # v1.318.0
        with:
          ruby-version: '${{ matrix.ruby }}'
      - name: Gather inital host info
        run: ext/bin/host-info
      - env:
          LEIN_PROFILES: ${{ matrix.lein-profile }}
          PDB_QUERY_OPTIMIZE_DROP_UNUSED_JOINS: ${{ matrix.drop-joins }}
        run: ci/bin/prep-and-run-in github ${{ matrix.flavor }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "${{ steps.computed.outputs.pdb-job-id }}.zip"
          path: |
            pg.log
            test.log
