---
name: main
on:
  pull_request: { branches: ['main'] }
  push:
    branches:
      - main

permissions:
  contents: read # minimal required permissions to clone repo

jobs:
  # We use "o" as the name to keep it short since the flavor repeats
  # it, and the current actions interface doesn't show very many
  # characters in the test names.
  o:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.flavor }} - Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        # Change the pb_test_gh_job_id definition below after any
        # additions/removals of matrix axes.  The flavor "/" is
        # converted to "_" in the pdb-job-id below.

        flavor:
          # terminus rspec tests
          - rspec/pup-main
          # agent, server, db integration tests
          - int/openjdk21/pup-main/srv-main/pg-18/rich
          - int/openjdk25/pup-main/srv-main/pg-18/rich


        os: [ubuntu-24.04]
        ruby: ['3.4']

        # Defaults for special-case influencing vars
        lein-profile: ['']
        drop-joins: ['']

        # Special cases
        include:
          # lint
          - flavor: lint/openjdk21
            os: ubuntu-24.04
            ruby: '3.4'

          # unit
          # jdk 25
          - flavor: core+ext/openjdk25/pg-18
            os: ubuntu-24.04
            ruby: '3.4'
          # jdk 21
          - flavor: core+ext/openjdk21/pg-18
            os: ubuntu-24.04
            ruby: '3.4'

    steps:
      - name: Compute job outputs
        id: computed
        run: |
          # This id must be unique across all jobs
          pdb_test_gh_job_id="${{ matrix.os }}/${{ matrix.flavor }}/${{ matrix.ruby }}"
          pdb_test_gh_job_id="${pdb_test_gh_job_id//\//_}"
          pdb_test_gh_job_id+="_${{ matrix.lein-profile }}"
          pdb_test_gh_job_id+="_${{ matrix.drop-joins }}"

          echo "day=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"
          echo "pdb-job-id=$pdb_test_gh_job_id" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version: '${{ matrix.ruby }}'
      - name: Output Ruby Environment
        run: bundle env
      - uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        with:
          key: |
            ${{ matrix.flavor }}
            ${{ runner.os }}
            ${{ hashFiles('**/Gemfile') }}
            ${{ hashFiles('**/project.clj') }}
            ${{ steps.computed.outputs.day }}
            %{{ matrix.ruby }}
          path: |
            ci/local/jdk
            vendor/bundle/ruby
            ~/.m2/repository
            ~/Library/Caches/Homebrew
      - name: Gather inital host info
        run: ext/bin/host-info
      - env:
          LEIN_PROFILES: ${{ matrix.lein-profile }}
          PDB_QUERY_OPTIMIZE_DROP_UNUSED_JOINS: ${{ matrix.drop-joins }}
          NO_ACCEPTANCE: true
        run: ci/bin/prep-and-run-in github ${{ matrix.flavor }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "${{ steps.computed.outputs.pdb-job-id }}.zip"
          path: |
            pg.log
            test.log

  build:
    name: build openvoxdb
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
      - name: checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive
          fetch-depth: 0 # So we fetch all history and tags and can build non-tagged versions
      - name: setup java
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: 'temurin'
          java-version: 25
      - name: setup ruby
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version: '4.0'
          bundler-cache: true
      - id: docker-cache
        uses: actions/cache/restore@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        with:
          path: /tmp/ezbake-builder.tar
          key: docker-ezbake-${{ hashFiles('Dockerfile') }}
      - name: load or build docker image
        run: |
          if [[ -f /tmp/ezbake-builder.tar ]]; then
            docker load -i /tmp/ezbake-builder.tar
          else
            docker build -t ezbake-builder .
            docker save ezbake-builder -o /tmp/ezbake-builder.tar
          fi
      - uses: actions/cache/save@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        if: always() && steps.docker-cache.outputs.cache-hit != 'true'
        with:
          path: /tmp/ezbake-builder.tar
          key: docker-ezbake-${{ hashFiles('Dockerfile') }}
      - name: build it
        run: bundle exec rake vox:build
      - name: get version
        id: version
        run: |
          DESCRIBE=$(git describe --abbrev=9)
          echo "describe=${DESCRIBE//-/.}" >> $GITHUB_OUTPUT
      - name: Upload build artifacts
        id: upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: openvoxdb-${{ steps.version.outputs.describe }}.zip
          path: output/
          retention-days: 1 # quite low retention, because the artifacts are quite large
          overwrite: true # overwrite old artifacts if a PR runs again (artifacts are per PR * per project)
      - name: Find existing comment
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4.0.0
        if: github.event.pull_request.head.repo.full_name == github.repository
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- build-artifacts -->'
      - name: Add or update comment
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        if: github.event.pull_request.head.repo.full_name == github.repository
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |-
            <!-- build-artifacts -->
            The rpm/deb packages and the JAR file for openvoxdb are available in a zip archive:
            ${{ steps.upload.outputs.artifact-url }}

  termini-rspec:
    name: openvoxdb-termini RSpec
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive
      - name: setup ruby
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Run RSpec
        run: bundle exec rspec spec -fd
        working-directory: puppet

  tests:
    needs:
      - o
      - build
      - termini-rspec
    runs-on: ubuntu-24.04
    name: Test suite
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
